test : venv
	source venv/bin/activate && python3 a.py

install :
	python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt

clean :
	rm -rf venv __pycache__ chiffrement.pdf
